services:
  db-postgres:
    container_name: ticket-service-db
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ticket-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${TICKET_SERVICE_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5